version: '3.7'
services:
    airflow:
        build:
            context: airflow
            dockerfile: Dockerfile
            args:
                - AIRFLOW_HOME=$AIRFLOW_HOME
                - USER_ID=$USER_ID
                - GROUP_ID=$GROUP_ID
        environment:
            - GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT
            - PYTHONPATH=$AIRFLOW_HOME/dags
            - AIRFLOW__CORE__DAGS_FOLDER=$AIRFLOW_HOME/dags
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:///$AIRFLOW_HOME/airflow.db
            - AIRFLOW__CORE__LOAD_EXAMPLES=FALSE
            - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=TRUE
        volumes:
            - ./airflow/dags:$AIRFLOW_HOME/dags
        ports:
            - 8080:8080

    metabase:
        image: metabase/metabase:v0.37.2
        ports:
            - 3000:3000
