version: '3.7'
services:
    postgres:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: superset
            POSTGRES_PASSWORD: superset
            POSTGRES_DB: superset

    superset:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres
        environment:
            - GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT
            - MAPBOX_API_KEY=$MAPBOX_API_KEY
            - SUPERSET_SQL_ALCHEMY=postgresql+psycopg2://superset:superset@postgres:5432/superset
        ports:
            - 8088:8088
        volumes:
            - ./dashboards:/opt/superset/dashboards
